<?php
namespace App\Repositories\Validators\Table_name;
use Prettus\Validator\LaravelValidator;

/**
 * Created by PhpStorm.
 * User: trinm
 * Date: 28/05/2019
 * Time: 08:52
 */
class UpdateTablenameValidator extends LaravelValidator
{
    public function getRules($action = null)
    {
        $this->rules = [
          "table_name" => "required|max:255"
        ];
        return parent::getRules($action); // TODO: Change the autogenerated stub
    }
}