<?php
namespace App\Repositories\Validators\Row_value;
use Prettus\Validator\LaravelValidator;

/**
 * Created by PhpStorm.
 * User: trinm
 * Date: 28/05/2019
 * Time: 16:19
 */
class CreateRowvalueValidator extends LaravelValidator
{
    public function getRules($action = null)
    {
        $this->rules = [
          'value' => 'required',
        ];
        return parent::getRules($action); // TODO: Change the autogenerated stub
    }
    
    public function getMessages()
    {
        $this->messages = [
          'value.required' => 'You must enter value',  
        ];
        return parent::getMessages(); // TODO: Change the autogenerated stub
    }
}